//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthenticationToken
    {
        public int Id { get; set; }
        public string Token { get; set; }
        public System.Guid AuthorId { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public byte Status { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
